mysite/mysite/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views

urlpatterns = [
    path("login/",auth_views.LoginView.as_view(template_name="users/login.html"),name="login"),
    path("logout/",auth_views.LogoutView.as_view(template_name="users/logout.html"),name="logout"),
    path("register/",include("users.urls")),
    path("polls/",include('polls.urls')),
    path('admin/', admin.site.urls),
] 

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

mysite/polls/urls.py
from django.urls import path
from . import views
app_name='polls'
urlpatterns = [
                path('',views.IndexView.as_view(),name='index'),
                path('<int:pk>/',views.DetailView.as_view(),name='detail'),
                path('<int:pk>/results/',views.ResultsView.as_view(),name='results'),
                path('<int:question_id>/vote/',views.vote,name='vote')
            ]

mysite/users/urls.py
from django.urls import path
from . import views

app_name="users"
urlpatterns = [
                path('',views.register,name='register'),
                path('profile/',views.profile,name='profile'),
                ]

mysite/polls/models.py
from django.db import models
from datetime import datetime,timedelta
from django.utils import timezone

# Create your models here.
class Question(models.Model):
    def __str__(self):
        return self.question_text

    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date_published')

    def was_published_recently(self):
        now=timezone.now()
        return now >= self.pub_date >= timezone.now()-timedelta(days=1)

class Choice(models.Model):
    def __str__(self):
        return self.choice_text
        
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)
    

mysite/users/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.
class Profile(models.Model):
    user = models.OneToOneField(User,on_delete=models.CASCADE)
    image = models.ImageField(default="default.jpg",upload_to="profile_pics")
    def __str__(self):
        return f"{self.user.username} Profile"

mysite/users/forms.py
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django import forms

class UserRegisterForm(UserCreationForm):
    email=forms.EmailField()

    class Meta:
        model=User
        fields = ["username","email","password1","password2"]

mysite/polls/views.py
from django.shortcuts import get_object_or_404, render
from django.http import Http404, HttpResponse, HttpResponseRedirect
from .models import Question,Choice
from django.template import loader
from django.urls import reverse
from django.views import generic
from django.utils import timezone
from django.contrib.auth.decorators import login_required

# Create your views here.

class IndexView(generic.ListView):
    template_name = 'polls/index.html'
    context_object_name = 'latest_question_list'

    def get_queryset(self):
        """Return the last five published questions."""
        return Question.objects.filter(pub_date__lte=timezone.now()).order_by('-pub_date')[:5]
    # return HttpResponse("Hello folks! You are at polls index :)")


class DetailView(generic.DetailView):
    model = Question
    template_name = 'polls/detail.html'
    def get_queryset(self):
        """
        Excludes any questions that aren't published yet.
        """
        return Question.objects.filter(pub_date__lte=timezone.now())


class ResultsView(generic.DetailView):
    model = Question
    template_name = 'polls/results.html'

def vote(request,question_id):
    question = get_object_or_404(Question,pk=question_id)
    try:
        selected_choice = question.choice_set.get(pk=request.POST["choice"])
    except (KeyError, Choice.DoesNotExist):
        return render(request, 'polls/detail.html', {"question":question,
                                            "error_message":"You didn't select a choice."})
    else:
        selected_choice.votes+=1
        selected_choice.save()
        return HttpResponseRedirect(reverse('polls:results',args=(question.id,)))

mysite/users/views.py
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render,redirect
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.decorators import login_required
from .forms import UserRegisterForm
from django.contrib import messages

# Create your views here.
def register(request):
    if request.method=="POST":
        form= UserRegisterForm(request.POST)
        if form.is_valid():
            form.save()
            user = form.cleaned_data.get("username")
            messages.success(request,f"Your account {user} has been registered. You can now log in ")
            return redirect('login')
    else:
        form = UserRegisterForm()
    return render(request,"users/register.html",{'form':form})
    return HttpResponse("Welcome to register page")

@login_required
def profile(request):
    return render(request,"users/profile.html")

mysite/polls/templates/polls/detail.html
<form action="{% url 'polls:vote' question.id %}" method="post">
{% csrf_token %}
<fieldset>
    <legend><h1>{{ question.question_text }}</h1></legend>
    {% if error_message  %}
        <p><strong>{{ error_message }}</strong></p>
    {% endif %}

    {% for choice in question.choice_set.all %}
        <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{choice.id}}">
        <label for="choice{{forloop.counter}}">{{ choice.choice_text }}</label><br>
    {% endfor %}
</fieldset>
<input type="submit" value="Vote">
</form>

mysite/polls/templates/polls/index.html
{% if user.is_authenticated %}
    <div>{{user.username}}</div>
    <a href="{% url 'logout' %}">Logout</a>
{% else %}
    <a href="{% url 'login' %}">Login</a>

{% endif %}



{% if latest_question_list %}
    <ul>
    {% for question in latest_question_list %}
        <li><a href="{% url 'polls:detail' question.id %}">{{ question.question_text }}</a></li>
    {% endfor %}
    </ul>
{% else %}
    <p>No polls are available.</p>
{% endif %}

mysite/polls/templates/polls/results.html
<h1>{{ question.question_text}}</h1>

<ul>
    {% for choice in question.choice_set.all %}
    <li>{{ choice.choice_text}} -- {{choice.votes}} vote{{choice.votes|pluralize}}</li>
    {% endfor %}
</ul>
<a href="{% url 'polls:detail' question.id %}">Vote again?</a>

mysite/users/templates/users/login.html
<form method="POST">
    {% csrf_token %}
    <fieldset>
        {{form}}
    </fieldset>
    <button>Submit</button>
</form>
<div>Not a user yet?</div>
<div>
    <a href="{% url 'users:register' %}">Sign up</a>
</div>

mysite/users/templates/users/logout.html
<h2>You have been logged out</h2>
<a href="{% url 'login' %}">Login Again</a>

mysite/users/templates/users/profile.html
<h2>{{user.username}}</h2>
<h1>{{user.email}}</h1>

mysite/users/templates/users/register.html
<form method="POST">
    {% csrf_token %}
    <fieldset>
        {{form}}
    </fieldset>
    <button>Submit</button>
</form>
<div>Already a user?</div>
<a href="{% url 'login' %}">Sign In</a>